export const API_ERROR_CODES = {
  USER: {
    DUPLICATE: 'ERROR:USER-DUPLICATE',
    NOT_FOUND: 'ERROR:USER-NOT_FOUND',
    INACTIVE: 'ERROR:USER-INACTIVE',
    EDIT_ONLY_YOURSELF: 'ERROR:USER-EDIT_ONLY_YOURSELF',
    WRONG_PASSWORD: 'ERROR:USER-WRONG_PASSWORD',
    NOT_LOGGED_IN: 'ERROR:USER-NOT_LOGGED_IN',
    ALREADY_ACTIVATED: 'ERROR:USER-ALREADY_ACTIVATED'
  },
  AUTH: {
    INVALID_SPECIAL_CODE: 'ERROR:AUTH-INVALID_SPECIAL_CODE',
    NO_AUTH_HEADER: 'ERROR:AUTH-NO_AUTH_HEADER',
    WRONG_AUTH_TYPE: 'ERROR:AUTH-WRONG_AUTH_TYPE',
    NO_TOKEN: 'ERROR:AUTH-NO_TOKEN',
    NO_TOKEN_PAYLOAD: 'ERROR:AUTH-NO_TOKEN_PAYLOAD',
    INVALID_TOKEN: 'ERROR:AUTH-INVALID_TOKEN',
    EMPTY_CREDENTIALS: 'ERROR:AUTH-EMPTY_CREDENTIALS'
  },
  SESSION: {
    EMPTY: 'ERROR:TOKEN-EMPTY',
    WRONG_DEVICE: 'ERROR:TOKEN-WRONG_DEVICE',
    EXPIRED: 'ERROR:TOKEN-EXPIRED',
  },
  COMMON: {
    UNKNOWN: 'ERROR:SYSTEM-UNKNOWN!',
    HTTP: 'ERROR:SYSTEM-HTTP_EXCEPTION',
    EMPTY_EMAIL: 'ERROR:SYSTEM-EMAIL_REQUIRED',
    EMPTY_PARAM: 'ERROR:SYSTEM-EMPTY_PARAM'
  },
  CODE: {
    INVALID: 'ERROR:CODE-INVALID',
    UNKNOWN: 'ERROR:CODE-UNKNOWN',
    EXPIRED: 'ERROR:CODE-EXPIRED',
    WRONG_RELATED_TO: 'ERROR:CODE-NOT_YOURS_BITCH'
  },
  DATABASE: {
    DUPLICATE: 'ERROR:DATABASE-DUPLICATE'
  },
  VALIDATION: 'ERROR:VALIDATION',
  HTTP: {
    '400': 'ERROR:HTTP-BAD_REQUEST',
    '401': 'ERROR:HTTP-UNAUTHORIZED',
    '403': 'ERROR:HTTP-FORBIDDEN_RESOURCE',
    '404': 'ERROR:HTTP-NOT_FOUND',
  },

  LICENSE: {
    NOT_FOUND: 'ERROR:LICENSE-NOT_FOUND',
    ALREADY_EXIST: 'ERROR:LICENSE-ALREADY_EXIST'
  },

  WORKSPACE: {
    NOT_FOUND: 'ERROR:WORKSPACE-NOT_FOUND',
    NO_ACCESS: 'ERROR:WORKSPACE-NO_ACCESS',
    ALREADY_INITIATED: 'ERROR:WORKSPACE-ALREADY_INITIATED'
  },

  FEATURE: {
    NOT_AVAILABLE: 'ERROR:FEATURE-NOT_AVAILABLE',
    NOT_FOUND: 'ERROR:FEATURE-NOT_FOUND'
  },

  FEATURE_ASSIGNMENT: {
    NOT_AVAILABLE: 'ERROR:FEATURE-NOT_AVAILABLE',
    NOT_FOUND: 'ERROR:FEATURE-NOT_FOUND',
    ALREADY_EXIST: 'ERROR:FEATURE-ALREADY_EXIST'
  },

  PERMISSION: {
    NOT_FOUND: 'ERROR:PERMISSION-NOT_FOUND',
    NONE_AVAILABLE: 'ERROR:PERMISSIONS-NONE_AVAILABLE',
    WRONG_TYPE: 'ERROR:PERMISSIONS-WRONG_TYPE'
  },

  RECORD_SECURITY: {
    NOT_FOUND: 'ERROR:RECORD_SECURITY-NOT_FOUND',
    NO_ACCESS: 'ERROR:RECORD_SECURITY-NO_ACCESS'
  },

  PAGE: {
    NOT_FOUND: 'ERROR:PATE-NOT_FOUND'
  },

  METADATA: {
    OBJECT: {
      NOT_FOUND: 'ERROR:METADATA:OBJECT-NOT_FOUND',
    },
    FIELD: {
      NOT_FOUND: 'ERROR:METADATA:FIELD-NOT_FOUND',

    }
  },

  ROLE : {
    PARENT: {
      NOT_FOUND: 'ERROR:ROLE:PARENT-NOT_FOUND'
    }
  }
}